### ISSUE TITLE
Error install searx.sh

### ISSUE THREAD

**Issue by gghsocce** [goshawk22/searxng-installation#1]
Hi ,
 i got this messsage error when i launch the searx.sh install : `./utils/searx.sh install all`

`ls: cannot access '/root/searxng': Permission denied`
`ERROR: ./utils/searx.sh: line 469: user 'searx' missed read permission: /root/searxng`

**Comment by gghsocce** [comment]
I'am running the install script as root user !

**Comment by goshawk22** [comment]
Try cloning searxng to your users home folder, not the root home folder.
Instead of using su to do everything as root, use sudo from your user account.

**Comment by goshawk22** [comment]
Closing due to lack of response.
