### ISSUE TITLE
Update process

### ISSUE THREAD

**Issue by pm64** [goshawk22/searxng-installation#2]
Phenomenal guide, thank you for publishing this.

One thing that isn't covered is the update process. When updates to SearXNG are released, what's the recommended way of pulling these into the server?

**Comment by goshawk22** [comment]
I normally just run `git pull` to update the local repo from git and then you just have to run `sudo -H ./utils/searxng.sh instance update`. I'll add it in now - thanks for pointing it out.

**Comment by goshawk22** [comment]
Closing as information has been added to notes.
